### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cancel'

### ISSUE THREAD

**Issue by LAD1** [RuslanUC/RemoteAuthClient#1]
All of a sudden that error has started appearing, even when removing on_cancel from the code, any fixes?

**Comment by RuslanUC** [comment]
Discord changed remote auth gateway version. I fixed error on github, but i cant upload new version to pypi now, but tomorrow i will upload it.

**Comment by RuslanUC** [comment]
I uploaded new version.

`pip install remoteauthclient==1.3`
