### ISSUE TITLE
Attributerror:  self-_heartbeatTask has no attribute cancel()

### ISSUE THREAD

**Issue by FuckingToasters** [RuslanUC/RemoteAuthClient#10]
Hello, a few weeks ago this code have worked fine, i don't think i changed anything on my side. This error happen when the QR Code should be generated. Seems like ` self-_heartbeatTask` is somehow defined with `None`.

Anyone may got a solution for this issue?

```py
class RemoteAuthClient:
    def __init__(self):
        self.initCrypto()
        self._heartbeatTask = None
        self.on_fingerprint = self.ev
        self.on_userdata = self.ev
        self.on_token = self.ev
        self.on_cancel = self.ev
        self.on_timeout = self.ev

if p["op"] == "hello":
    await self.send({"op": "init", "encoded_public_key": self.publicKeyString}, ws)
    self._heartbeatTask = asyncio.get_event_loop().create_task(self.sendHeartbeat(p["heartbeat_interval"], ws))

self._heartbeatTask.cancel()
```

**Comment by FuckingToasters** [comment]
> Update remoteauthclient to latest version (1.4.0b3)

changed nothing... i even tried to install direclty from this github page by using `pip install -U git+"https://github.com/RuslanUC/RemoteAuthClient"`

**Comment by FuckingToasters** [comment]
> Are you importing the remoteauthclient class or do you have the RemoteAuthClient (and User) class in your code?

It's in the code i guess

**Comment by RuslanUC** [comment]
Remove RemoteAuthClient and User classes from code and add import (`from remoteauthclient import RemoteAuthClient`)

**Comment by FuckingToasters** [comment]
> Remove RemoteAuthClient and User classes from code and add import (`from remoteauthclient import RemoteAuthClient`)

After i've done this, the issue just moved to the class in the libary:
```py
Task exception was never retrieved
future: <Task finished name='Task-26' coro=<RemoteAuthClient.run() done, defined at C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\remoteauthclient\remoteauthclient.py:67> exception=AttributeError("'NoneType' object has no attribute 'cancel'")>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\remoteauthclient\remoteauthclient.py", line 108, in run
    self._heartbeatTask.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'
```

**Comment by FuckingToasters** [comment]
Issue solved after uninstalling remoteauthclient and installing again with a new version specified `remoteauthclient==1.4.0b3`
