### ISSUE TITLE
Обход каптчи не работает

### ISSUE THREAD

**Issue by justNice** [RuslanUC/RemoteAuthClient#18]
Можем пойти в дискорд для более простого общения? Nice🌙#1052
А так кратко:
С помощью AioHcaptcha получаю ключ каптчи и отправляю в реквест, но выдает ошибку 400.

**Comment by RuslanUC** [comment]
Добавьте это перед `RemoteAuthClient()` и отправьте файл bot.log после попытки авторизации:
```python
import logging
logging.basicConfig(filename="bot.log", filemode="a", level=logging.DEBUG)
```

**Comment by RuslanUC** [comment]
> Код

А что это за код и почему вы не используете существующие методы из RemoteAuthClient?

**Comment by RuslanUC** [comment]
Попробуйте использовать код из примеров (в README.md), также попробуйте обновить async-hcaptcha (или установить версию с гитхаба). Так же проблема может быть в том, что дискорд как-то усложняет процесс получения токена из ticket (как именно - пока не понятно)

**Comment by 10kkm** [comment]
попробуйте использовать anticaptcha-official
