### ISSUE TITLE
error in "pending_login"

### ISSUE THREAD

**Issue by okcuuuu** [RuslanUC/RemoteAuthClient#2]
Task exception was never retrieved
future: <Task finished name='Task-23' coro=<start.<locals>.verification_callback.<locals>.RemoteAuthClient.run() done, defined at c:\main.py:132> exception=AssertionError()>
Traceback (most recent call last):
  File "c:\main", line 170, in run
    assert resp.status == 200
AssertionError

**Comment by RuslanUC** [comment]
I cant reproduce error. Can you install remoteauthclient from dev branch and send your script output?

**Comment by RuslanUC** [comment]
Most likely fixed in 1.4.0
