### ISSUE TITLE
What to do if this error occurs

### ISSUE THREAD

**Issue by andewq** [RuslanUC/RemoteAuthClient#5]
![Снимок экрана 2022-09-22 172351](https://user-images.githubusercontent.com/88948071/191773645-f83cf1f3-6d63-49f9-a95e-098ad69fdcd4.png)

**Comment by RuslanUC** [comment]
This is captcha response. Update remoteauthclient to 1.4.0b3 and use proxy or solve captcha (examples in readme.md)

**Comment by RuslanUC** [comment]
Most likely fixed in 1.4.0
